name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
      ARGOCD_DOMAIN: argocd.sutthiporn.dev

    steps:
      - name: 🔄 Checkout source code
        uses: actions/checkout@v3

      # Docker Buildx
      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker Login
      - name: 🔐 Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}

      # Build + Push Angular
      - name: 📦 Build and Push Angular (frontend)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_USER }}/cashnote-frontend:latest

      # Build + Push .NET API
      - name: 📦 Build and Push .NET API (backend)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: ${{ env.DOCKER_USER }}/cashnote-backend:latest

      # Setup kubectl
      - name: 📡 Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      # Set KUBECONFIG (จาก GitHub Secret)
      - name: Set kubeconfig from secret
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml

      # Apply ArgoCD Application YAML
      - name: 🚀 Apply ArgoCD Applications
        run: |
          kubectl apply -f k8s/argocd-application.yaml -n argocd

      # Trigger ArgoCD Sync via API
      - name: 🔁 Trigger ArgoCD Sync
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
            https://${{ env.ARGOCD_DOMAIN }}/api/v1/applications/cashnote-frontend/refresh

          curl -X POST -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
            https://${{ env.ARGOCD_DOMAIN }}/api/v1/applications/cashnote-backend/refresh
